### PR TITLE
Upgrade to Go 1.22.1

### PR DESCRIPTION
**Pull request by drevell**
Some Go CVEs were just announced, and they're fixed in 1.22.1, so let's upgrade.

I dunno if our GitHub Actions will support 1.22.1 yet, but let's try.

### CODE REVIEW

**Comment by drevell** [comment]
Looks like we can't use Go 1.22 yet because CodeQL doesn't support it (https://github.com/github/roadmap/issues/918). Converting this PR to "draft" state for now.

**Comment by sethvargo** [comment]
@drevell mind if I take this over? I'm doing it in other repos and I know what needs to change to make CodeQL happy.

**Comment by drevell** [comment]
> @drevell mind if I take this over? I'm doing it in other repos and I know what needs to change to make CodeQL happy.

That would be very welcome, thanks.

**Comment by sethvargo** [comment]
@drevell should be good now. I did everything in a single commit so you can see the diff more easily.

**Comment by drevell** [comment]
@sethvargo LGTM. I can't approve though because it's my PR :)

**Review by sethvargo — APPROVED** [review]

**Comment by sethvargo** [comment]
There's definitely a fun bug where I can approve my own changes that I added to your branch, but... approved 🚢 🚀

**Pull request merged**
