### PR TITLE
Allow YAML decoding to change depending on apiVersion

### PR DESCRIPTION
**Pull request by drevell**
This is a hack, but I think it's the best option we have. It's a hack because it uses mutable global state where it really doesn't theoretically need to, but we're limited by our libraries.

In this PR we create a global variable that stores the apiVersion of the YAML document currently being parsed. We add a mutex to ensure that only one document can be parsed at a time.

Alternatives considered:

 - threadlocals: don't exist in Go (https://github.com/golang/go/issues/18802)
 - use a different YAML parser library that plumbs a context.Context to UnmarshalYAML(): github.com/goccy/go-yaml almost worked, but it doesn't provide line/column position information, which is a dealbreaker.
 - Just skip it and don't provide schema versioning: the schema would turn into a mess over time.
 - Write our own YAML decoder, potentially reusing https://pkg.go.dev/github.com/goccy/go-yaml/parser: would be lots of work.

This is a prelude to #130.

### CODE REVIEW

**Comment by sethvargo** [comment]
Thanks Dave - my initial reaction is that we should just update the parsing logic to handle both arrays and single string values, passing everything as a slice thereafter (with string values being single-item slices).

If we really want versioned parsers, then I think we version _the parser itself_, which would have different decoding logic. Then, during the top-level parse, we'd have something like:

```go
if parsed.apiVersion == "1" {
  return v1parser.Parse(node)
else if parsed.apiVersion == "2" {
  return v2parser.Parse(node)
}
}
```

But I'm not super convinced we need to introduce versioning at this stage (but I'm open to being told I'm wrong 😄).

**Comment by kevya-google** [comment]
> Thanks Dave - my initial reaction is that we should just update the parsing logic to handle both arrays and single string values, passing everything as a slice thereafter (with string values being single-item slices).

So how long would this change be kept moving forward, would there be a point where we remove support for the old version? Or would we keep both indefinitely?

**Comment by drevell** [comment]
> Thanks Dave - my initial reaction is that we should just update the parsing logic to handle both arrays and single string values, passing everything as a slice thereafter (with string values being single-item slices).
> 
> If we really want versioned parsers, then I think we version _the parser itself_, which would have different decoding logic. Then, during the top-level parse, we'd have something like:
> 
> ```go
> if parsed.apiVersion == "1" {
>   return v1parser.Parse(node)
> else if parsed.apiVersion == "2" {
>   return v2parser.Parse(node)
> }
> }
> ```
> 
> But I'm not super convinced we need to introduce versioning at this stage (but I'm open to being told I'm wrong 😄).

Yeah, I see what you mean, and that would work. I see some tradeoffs here:

Option 1: Versioned parser:
 - Pro: each parser is easy to read
 - Con: absolutely massive copypasta. Discourages versioning because each version incurs new copypasta.

Option 2: Accept either list-of-string or list-of-object:
 - Pro: easy to code, no copypasta, no versioning concerns
 - Con: devex for YAML authors. The user just wants to know "what's the type of this field?" and the answer is "weep while trying to understand our polymorphic glory which is so easy to use that you're scrolling through examples trying to find something that you think might be what you're looking for but you're not sure." Like GitHub Actions (maybe k8s too, I dunno). I think polymorphic cleverness is often a misfeature in YAML schemas, but maybe I'm in the minority.

Option 3: The locked-global approach:
 - Pro: simple, avoids copypasta. Good devex for YAML authors (the right way to do it is the only way to do it).
 - Con: locking hackery. Only works for small changes to the schema. Combines logic for multiple schema versions in the same parser code.

So I think we'll have two kinds of schema change:
 - Minor tweaks like this one that don't warrant a new revision of the models, where Option 3 is appropriate.
 - Major tweaks that DO warrant a new revision of the models, where Option 1 is appropriate.

Can you live with that?

@sethvargo

**Comment by yolocs** [comment]
> Option 1: Versioned parser:

> Pro: each parser is easy to read
> Con: absolutely massive copypasta. Discourages versioning because each version incurs new copypasta.

At first glance, I'm definitely a fan of this. Could you help me understand why copypasta will be a must? Is it possible to refactor common yaml parse functionality out to be a common lib, and have each versioned parser use it?

**Comment by sethvargo** [comment]
> > Option 1: Versioned parser:
> 
> > Pro: each parser is easy to read
> > Con: absolutely massive copypasta. Discourages versioning because each version incurs new copypasta.
> 
> At first glance, I'm definitely a fan of this. Could you help me understand why copypasta will be a must? Is it possible to refactor common yaml parse functionality out to be a common lib, and have each versioned parser use it?

I had a similar question. Could we do:

```go
package parser


type V1 struct {
  //...
}

func (v *V1) Thing()
func (v *V1) OtherThing()

type V2 struct {
  V1
}

// Only override OtherThing parsing.
func (v *V2) OtherThing()
```


> - Minor tweaks like this one that don't warrant a new revision of the models, where Option 3 is appropriate.
> - Major tweaks that DO warrant a new revision of the models, where Option 1 is appropriate.
> Can you live with that?

To be honest, the locked global feels _way_ more complex and error-prone than a little polymorphism. We can also aggressively unit test the polymorphism to handle edge cases. I hear your point about DevEx, but this is pretty common (most k8s things are []string in the data model, but accept single-string values and array-string values in the YAML).

**Comment by drevell** [comment]
OK, I can accept the polymorphic approach. That doesn't require any special versioning code so I'll close this.

**Pull request closed without merging**
